packages:
    - apps/mobile
    - apps/partners
    - apps/admin-seed-script
    - apps/admin
    - packages/api
    - packages/auth
    - packages/admin-api
    - packages/partner-api
    - packages/db
    - packages/config/*
